version: "3.9"
services:
  db:
    container_name: "KIC_DB"
    build:
      context: ./db
      dockerfile: Dockerfile
    #    image: mariadb:10.9.3
    environment:
      MYSQL_DATABASE: 'ssbd03'
      MYSQL_ROOT_PASSWORD: 'cyberpunk2077'
      MYSQL_USER: 'ssbd03'
      MYSQL_PASSWORD: 'cyberpunk2077'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    container_name: "KIC_APP"
    depends_on: [ "db" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        username: "admin"
        password: "admin"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    volumes:
      - app_data:/opt/jboss/wildfly/standalone/deployments
volumes:
  db_data:
    driver: local
  app_data:
    driver: local