version: "3.9"
services:
  db:
    image: mariadb:10.9.3
    container_name: "KIC_DB"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  app:
    container_name: "KIC_APP"
    depends_on: [ "db" ]
    build:
      context: app
      args:
        username: ${WILDFLY_USERNAME}
        password: ${WILDFLY_PASSWORD}
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    volumes:
      - app_data:/opt/bitnami/wildfly/standalone
volumes:
  db_data:
    driver: local
  app_data:
    driver: local