services:
  db:
    image: mariadb:10.9.3
    container_name: "KIC_DB"
    restart: always
    networks:
      - db_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  app:
    container_name: "KIC_APP"
    restart: always
    networks:
      - db_network
      - http_network
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        username: ${WILDFLY_USERNAME}
        password: ${WILDFLY_PASSWORD}
    volumes:
      - app_data:/opt/bitnami/wildfly/standalone:rw
      - ./app:/docker-entrypoint-initdb.d:ro
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 3
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:1.23.2
    restart: always
    container_name: "KIC_PROXY"
    networks:
      - http_network
    ports:
      - "9000:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/tua202203.crt:/etc/nginx/ssl/tua202203.crt:ro
      - ./proxy/tua202203.key:/etc/nginx/ssl/tua202203.key:ro
    depends_on:
        app:
            condition: service_healthy

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  proxy_data:
    driver: local
networks:
  db_network: {}
  http_network: {}
