CREATE TABLE IF NOT EXISTS test (test VARCHAR (50) NOT NULL);

GRANT ALL ON ALL TABLES IN SCHEMA "public" TO ssbd03auth;
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO ssbd03mop;
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO ssbd03mok;
